
name: Continuos Integration

on: [ pull_request ]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install dependencies
        run: yarn bootstrap

      - name: Linting
        run: yarn lint

      - name: Unit Test
        run: yarn test
